name: $(Date:yyyyMMdd)$(Rev:.r)-food-facts-agent

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - agents/food-facts-agent.yaml
      - pipelines/food-facts-agent-pipeline.yml

variables:
  - name: AZURE_SERVICE_CONNECTION
    value: 'ado-service-connection'
  - name: FOUNDRY_ENDPOINT
    value: 'https://adusa-poc-agent.services.ai.azure.com/api/projects/adusa-poc-agent'
  - name: AGENT_YAML_PATH
    value: 'agents/food-facts-agent.yaml'

pool:
  name: 'egen-agent-pool'

steps:
  - checkout: self

  - bash: |
      echo "🤖 Deploying Food Facts Agent"
      echo "📄 Agent: $(AGENT_YAML_PATH)"
      echo "🔗 Endpoint: $(FOUNDRY_ENDPOINT)"
    displayName: 'Show deployment info'

  - task: AzureCLI@2
    displayName: 'Deploy food-facts-agent'
    inputs:
      azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Setup Python environment
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -q --upgrade pip
        pip install -q -r requirements.txt

        # Deploy agent (uses DefaultAzureCredential with AzureCLI context)
        .venv/bin/python -m scripts.deploy_agent "$(FOUNDRY_ENDPOINT)" "$(AGENT_YAML_PATH)"
