name: $(Date:yyyyMMdd)$(Rev:.r)-openfoodfacts-connection

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/parameters/connections/openfoodfacts*
      - pipelines/openfoodfacts-connection-pipeline.yml

variables:
  - name: AZURE_SERVICE_CONNECTION
    value: 'ado-service-connection'
  - name: BICEPPARAM_FILE
    value: 'infrastructure/parameters/connections/openfoodfacts.bicepparam'

pool:
  name: 'egen-agent-pool'

steps:
  - checkout: self

  - bash: |
      echo "🔗 Deploying Open Food Facts Connection"
      echo "📄 Using bicepparam: $(BICEPPARAM_FILE)"
    displayName: 'Show deployment info'

  - task: AzureCLI@2
    displayName: 'Deploy openfoodfacts connection'
    inputs:
      azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Setup Python environment
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -q pyyaml

        # Deploy connection via Bicep
        python scripts/deploy_infrastructure.py foundry_connection --bicepparam $(BICEPPARAM_FILE)
